### ISSUE TITLE
Build error with vs2019

### ISSUE THREAD

**Issue by Gaojianli** [skypjack/uvw#150] opened 2019-05-15 15:56 UTC
I try to use `v1.16.0_libuv-v1.28` release on Visual Studio 2019, and I got following errors:
![image](https://user-images.githubusercontent.com/19235246/57790089-a92d4380-776c-11e9-9a11-0f7367e3f802.png)
Here are part of the compiler output:
```
1>------ Build started: Project: Server, Configuration: Debug x64 ------
1>pch.cpp
1>C:\source\Server\include\uvw\lib.hpp(68,1): error C3537:  you cannot cast to a type that contains 'auto'
1>C:\source\Server\include\uvw\lib.hpp(68,1): message :  This diagnostic occurred in the compiler generated function 'F *uvw::SharedLib::sym(std::string)'
1>C:\source\Server\include\uvw\lib.hpp(68,1): error C2100:  illegal indirection
1>C:\source\Server\include\uvw\lib.hpp(68,1): message :  This diagnostic occurred in the compiler generated function 'F *uvw::SharedLib::sym(std::string)'
1>C:\source\Server\include\uvw\thread.hpp(109,36): warning C4838:  conversion from 'uvw::Flags<uvw::Thread::Options>' to 'unsigned int' requires a narrowing conversion
1>C:\source\Server\include\uvw\thread.hpp(165,1): error C3537:  you cannot cast to a type that contains 'auto'
1>C:\source\Server\include\uvw\thread.hpp(165,1): message :  This diagnostic occurred in the compiler generated function 'T *uvw::ThreadLocalStorage::get(void) noexcept'
1>C:\source\Server\include\uvw\thread.hpp(165,1): error C2100:  illegal indirection
```
My `cl.exe` version is `Microsoft (R) C/C++ Optimizing Compiler Version 19.21.27619.1 for x64`

**Comment by Gaojianli** [comment] 2019-05-15 16:01
Here are my `pch.h`, I don't think there are any incompatible headers:
```cpp
#define _SILENCE_CXX17_RESULT_OF_DEPRECATION_WARNING
#ifndef PCH_H
#define PCH_H

// add headers that you want to pre-compile here
#include <uvw.hpp>
#include <string>
#include <rapidjson/document.h>
#include <rapidjson/writer.h>
#include <rapidjson/stringbuffer.h>
#include <list>
#include <iostream>
#include <mysql.h>
#include <vector>
#include "user.h"
#include "Word.h"
#include "md5.h"
#endif //PCH_H
```

**Comment by skypjack** [comment] 2019-05-15 16:28
Can you make a small, reproducible example I can run for my own?  
Otherwise I don't know how to reproduce it and I cannot look into the problem.

**Comment by Gaojianli** [comment] 2019-05-16 11:57
Here comes the [sample](https://us.gaojianli.me/Sample.zip) which are copied from `README.md`.
I tried to compile it on my computer and get this:
![image](https://user-images.githubusercontent.com/19235246/57852038-abe37380-7814-11e9-8066-0a4d98670232.png)

**Comment by skypjack** [comment] 2019-05-16 12:05
Side question: have you tried them without pch stuff?  
Currently all tests pass without problems on appveyor with the last vs, so it's likely that the problem is the pch itself.  
This question just to confirm it.

**Comment by refack** [comment] 2019-05-16 13:14
I've just run the sample code, it does fail with cl `19.21.27619.1` (a.k.a 16.1.0 Preview 3) but works just fine with `19.20.27508.1` (a.k.a. 16.0.3), so I'd say it's most likely a compiler bug.
Bug could be either that it compiles with `19.20` or that it fails with `19.21`, as I'd expect code to compile the same for a semver-minor version change.

**Comment by skypjack** [comment] 2019-05-16 13:22
Good to know, but what can I do with a compiler bug I cannot even reproduce?  
If you know of a workaround for this, I'm open to suggestions.

**Comment by refack** [comment] 2019-05-16 13:27
> Good to know, but what can I do with a compiler bug I cannot even reproduce?

First I would say, [report it](https://developercommunity.visualstudio.com/spaces/62/index.html), AFAIK the MSVC team would appreciate such feedback.
Meanwhile I'll try to figure out a workaround.

**Comment by Gaojianli** [comment] 2019-05-16 15:12
> Good to know, but what can I do with a compiler bug I cannot even reproduce?
> 
> First I would say, report it, AFAIK the MSVC team would appreciate such feedback.
> Meanwhile I'll try to figure out a workaround.

I have tried to report it [here](https://developercommunity.visualstudio.com/content/problem/571044/confusing-compile-error-illegal-indirection.html).

**Comment by skypjack** [comment] 2019-05-27 12:06
So, it's confirmed that the bug is in VS, right?  
I'll mark the issue as _won't fix_. Please, close it when the fix is upstream.  
Thanks.

**Comment by Gaojianli** [comment] 2019-05-28 17:31
>Peijie Chen [MSFT] :
A fix for this issue has been internally implemented and is being prepared for release16.3. We'll update you once it becomes available for download.

It seems that it will be fixed in `16.3`

**Comment by refack** [comment] 2019-05-28 23:14
I wasn't able to find a reasonable workaround ¯\\_(ツ)_/¯

**Comment by refack** [comment] 2019-05-28 23:40
FTR:
* v16.1.0 (i.e. CL 19.21.27702.2) - ❌ 
* v16.2.0 preview-1 (i.e. CL 19.22.27706.1) - ❌ 
* v16.0.3 (19.20.27508.1) - ✔️

**Comment by skypjack** [comment] 2019-05-29 09:10
> I wasn't able to find a reasonable workaround ¯\_(ツ)_/¯ (code-wise)

Don't worry, I failed as well. Being it an issue with the compiler, it makes sense anyway to wait for them to solve it. :+1: 
Thank you for your help. Really appreciated.

**Comment by Kaninchen221** [comment] 2019-09-09 14:52
I have this bug (with or without /Zc:twoPhase-, /permissive-) at:
<ul>
<li>v16.3.0 VS2019 Preview</li>
<li>v16.2.4 VS2019</li>
<li>v15.9.15 VS2017</li>
</ul>

**Comment by skypjack** [comment] 2019-09-09 15:08
They claim that [a fix is available](https://developercommunity.visualstudio.com/comments/693220/view.html) for VS2019. Time to close this issue?
Since it's a bug in VS, I cannot do much anyway.

**Comment by Merethiel** [comment] 2019-09-16 04:05
I was receieving the same error in VS 2019.  @skypjack I do have the most updated version of VS currently do you know if the update for the fix has been rolled out already because mine still has those same compiler errors.

**Comment by skypjack** [comment] 2019-09-16 09:19
No idea @Merethiel - I'm not using Windows and this problem doesn't really depend on me, so I cannot do much.
The issue is open only to track it and avoid duplicates but you should rather ask MS when they plan to accept valid C++ with their compiler.

**Comment by JadeVand** [comment] 2019-10-11 11:35
UVW Compiles successfully in the latest Visual Studio update 16.3.4

**Comment by skypjack** [comment] 2019-10-11 11:39
That's great @JadeVand thanks for pointing it out. Time to close this issue. :wink:

**Closed by skypjack** 2019-10-11 11:39 UTC
Labels: wontfix
